version: '2'
services:
  nodeapp:
    restart: always
    build:
      context: ./expressapp/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    stdin_open: true
    command: npm run dev 
    volumes:
      - ./expressapp:/code/
      #- /code/node_modules
 
